[package]
name = "jyutcitzi"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Vincent Tam"]
description = "A system for displaying Jyutcitzi characters (粵切字)."
repository = "https://github.com/VincentTam/riesketcher"
exclude = ["manual.typ", "manual.pdf"]
keywords = ["jyutping", "jyutcitzi", "cantonese"]
